/*
 * This Hyperlambda snippet demonstrates basic exception handling.
 * The `try` block attempts to throw an exception.
 * The `catch` block catches the exception and sets `.throws` to `true`.
 * Expected behavior: `.throws` should be `true` after execution.
 */

.throws:bool:false
try
   throw:foo
.catch
   set-value:x:@.throws
      .:bool:true
