// Use try with .catch and .finally to handle exceptions
try
   throw:Error occurred
.catch
   log.info:Caught the error
.finally
   log.info:Cleanup done
